### ISSUE TITLE
8" Radxa display on CM3 IO with mainline kernel

### ISSUE THREAD

**Issue by 03vmate** [radxa-pkg/radxa-overlays#306]
Trying to get the 8" Radxa display working on a CM3 IO with mainline kernel, 6.1 or 6.6 ideally(latest/.stable-6.6/.stable-6.1 in BSP).
The overlays in this repo won't compile for those, tried to modify it to work, but had no success. It compiles without errors now, but no display/mipi related things show up in dmesg.

Attached the modified overlay that builds but doesn't work.

Any help would be greatly appreciated.
[display.zip](https://github.com/radxa-pkg/radxa-overlays/files/15140165/display.zip)

**Comment by RadxaYuntian** [comment]
Unfortunately the device tree is tightly coupled with the kernel driver, so there is no guarantee that it will work across different kernels. CM3 IO is not listed as a supported product in bsp's mainline kernel profiles (it is commented out) so we do not expect the overlay will work there.

At this moment we do not have the resource to support mainline kernel on CM3 IO.
