### ISSUE TITLE
Radxa Display 10FHD on Armbian or Joshua Riek 24.04

### ISSUE THREAD

**Issue by MyVizDrake** [radxa-pkg/radxa-overlays#324]
SBC is Rock 5A 
Downloaded and compiled the Rock 5A Display10FHD source from here. Screen is functioning on JR’s 24.04 kernel (6.1.x) and Armbian’s current (5.10.160)

cannot get the touchscreen to work at all. What’s required for the touch in this DTS file to work?

**Comment by RadxaYuntian** [comment]
Dunno. Our overlays are designed and tested against our own kernel. Overlays is highly coupled with the specific device tree implementation, so you should compare the working & non working files to see if some nodes were changed.

You should also check if your kernel has the associated driver included, and whether it was loaded.
