### ISSUE TITLE
ROCK 2A => ROCK 2更名

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-pkg/radxa-overlays#333]
检查一下这里的overlay是否需要更新

**Comment by RadxaYuntian** [comment]
Overlay看来是不用更新，因为内核还是有独立的设备树

**Comment by CodeChenL** [comment]
除了，这四个文件的compatible没定义，其他感觉没啥问题
![image](https://github.com/radxa-pkg/radxa-overlays/assets/43897062/a973b472-f689-484b-ae60-62a76cd5de5c)

**Comment by RadxaYuntian** [comment]
有时候是因为没有对应的产品支持这些接口，所以就先unknown
