### ISSUE TITLE
rk3308-spi0-spidev makes armbian crash on startup

### ISSUE THREAD

**Issue by Grix** [radxa-pkg/radxa-overlays#345]
I don't know if this is strictly an issue with the overlay or the OS but I'm reporting it for the record.

If I try to add rk3308-spi0-spidev.dts to the official Armbian build (24.5.1 Noble Server) using the armbian-add-overlay tool, then the device no longer boots correctly. The heartbeat LED blinks for around 20 seconds while it boots, but then it stops, and I cannot connect to the device over ssh. Essentially the image becomes corrupt and I need to flash the OS again from scratch to make it work. Therefore I cannot retrieve any error logs etc either.

This only seems to be a problem with spi0, because the spi1 dts boots fine.

**Comment by RadxaYuntian** [comment]
Device tree overlay is strongly coupled with the base device tree, so they are not portable across kernels. We only guarantee that they work on our kernels on [compatible devices](https://github.com/radxa-pkg/radxa-overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/rk3308-spi0-spidev.dts#L7). The latter is guaranteed by our `rsetup` tool that will filter out incompatible options.

Currently we use a custom [device tree](https://github.com/radxa-repo/bsp/blob/main/linux/.stable-6.1/0025-rock-s0/0001-arm64-dts-add-radxa-s0.patch) for ROCK S0, which may not be the same as what Armbian uses.
