### ISSUE TITLE
rk3588系列 打开Enable UART2-M0失败

### ISSUE THREAD

**Issue by Ken-Vamrs** [radxa-pkg/radxa-overlays#375]
rk3588系列 打开Enable UART2-M0 失败，没有disabled fiq_debugger 导致引脚冲突
[   15.445526] rockchip-pinctrl pinctrl: pin gpio0-14 already requested by fiq-debugger; cannot claim for feb50000.serial
[   15.445550] rockchip-pinctrl pinctrl: pin-14 (feb50000.serial) status -22
[   15.445563] rockchip-pinctrl pinctrl: could not request pin 14 (gpio0-14) from group uart2m0-xfer  on device rockchip-pinctrl
[   15.445578] dw-apb-uart feb50000.serial: Error applying setting, reverse things back

**Comment by RadxaYuntian** [comment]
你确认UART2-M2也不行是么？那个overlay一直是这样关闭fiq_debugger的：https://github.com/radxa-pkg/radxa-overlays/commit/0190237f6a4aae0acbe4029ad372ac135070bcaf

**Comment by Ken-Vamrs** [comment]
> 你确认UART2-M2也不行是么？那个overlay一直是这样关闭fiq_debugger的：[0190237](https://github.com/radxa-pkg/radxa-overlays/commit/0190237f6a4aae0acbe4029ad372ac135070bcaf)

uart2m2这个正常，昨天可能没选好overlay，复测正常
root@rock-5t:/home/radxa# cat /boot/extlinux/extlinux.conf 

label l0
        menu label Debian GNU/Linux 12 (bookworm) 6.1.43-18-rk2312
        linux /boot/vmlinuz-6.1.43-18-rk2312
        initrd /boot/initrd.img-6.1.43-18-rk2312
        fdtdir /usr/lib/linux-image-6.1.43-18-rk2312/
        fdtoverlays  /boot/dtbo/rk3588-uart2-m2.dtbo

root@rock-5t:/home/radxa# ls /dev/ttyS2 
/dev/ttyS2

**Comment by RadxaYuntian** [comment]
能帮忙测试一下3566的overlay可以用么：https://github.com/radxa-pkg/radxa-overlays/commit/3f3b4b00710699738b902c89092a379b446d3d5f#diff-20ea4538207fb73cdddec6abecd95c9610e50b1b5860f619a0ef2e83f5a422f3L21
我现在在测试3588

**Comment by Ken-Vamrs** [comment]
> 能帮忙测试一下3566的overlay可以用么：[3f3b4b0#diff-20ea4538207fb73cdddec6abecd95c9610e50b1b5860f619a0ef2e83f5a422f3L21](https://github.com/radxa-pkg/radxa-overlays/commit/3f3b4b00710699738b902c89092a379b446d3d5f#diff-20ea4538207fb73cdddec6abecd95c9610e50b1b5860f619a0ef2e83f5a422f3L21) 我现在在测试3588

3568 替换之后不行,和3588 一样
[   13.697358] rockchip-pinctrl pinctrl: pin gpio0-24 already requested by fiq-debugger; cannot claim for fe660000.serial
[   13.697414] rockchip-pinctrl pinctrl: pin-24 (fe660000.serial) status -22
[   13.697446] rockchip-pinctrl pinctrl: could not request pin 24 (gpio0-24) from group uart2m0-xfer  on device rockchip-pinctrl
[   13.697485] dw-apb-uart fe660000.serial: Error applying setting, reverse things back
